name: BSD

on:
  push:
    branches:
      - aot_monorepo_compat
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ffigen:
    if: ${{false}}
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: dart-lang/setup-dart@v1
    - run: dart pub get
    - run: dart run ffigen --config lib/src/bsd/ffigen.yaml
    - uses: peter-evans/create-pull-request@v5
      if: github.event_name != 'pull_request'
      with:
        title: 'Regenerate BSD bindings'
        commit-message: 'Regenerate BSD bindings'
        add-paths: lib/src/bsd/ffigen.dart
        branch: regenerate/bsd
        delete-branch: true
    - run: |
        git diff > lib_src_bsd_ffigen.dart.diff
        [ -s lib_src_bsd_ffigen.dart.diff ] || rm lib_src_bsd_ffigen.dart.diff
    - uses: actions/upload-artifact@v3
      with:
        name: lib_src_bsd_ffigen.dart.diff
        path: lib_src_bsd_ffigen.dart.diff
        if-no-files-found: ignore
    - run: ./.github/scripts/check-outdated-files.sh
